import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/componentes/NavBar";
import { Footer } from "@/componentes/Footer";
import BotaoWhatsapp from "@/componentes/BotaoWhatsapp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-br"
      className={`h-full antialiased`}
    >
      <body className={`${geistSans.className} bg-white min-h-full flex flex-col`}>
        <NavBar/>
        {children}
        <Footer/>
        <BotaoWhatsapp/>
      </body>
    </html>
  );
}
